name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs -y -sSf | sh
        source $HOME/.cargo/env
    - name: Build project
      run: |
        cargo build --release
